services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      HOST: 0.0.0.0
      PORT: 4201
    expose:
      - "4201"
